### PR TITLE
Update Boost to 1.68.0 and add OSX build

### PR DESCRIPTION
**Pull request by spbennett**
- Pull in latest Boost release
- Add OSX build instructions
- Add build script for Linux/OSX
- Separate boost-dependencies into own source file (sorry cmd script)

### CODE REVIEW

**Comment by wwylele** [comment]
What is the reason for adding OSX/Linux stuff when this repo is meant to provide quick support specifically for windows?

**Comment by spbennett** [comment]
This change is just build tooling.  I added a `build.sh` for Linux/OSX to complement the existing `build.cmd` for Windows.  

This PR makes it easy to upgrade the Boost libs from a Linux or OSX host since the `build.cmd` script won't run natively as is on those OSes.  There are no platform specific changes to Boost in this PR.

**Comment by spbennett** [comment]
1.68.0 is still current if you'd like to use this PR.

**Comment by GPUCode** [comment]
This is outdated at this point, closing

**Pull request closed without merging**
