### PR TITLE
Get rid of Latin1 "smart quotes" in a file

### PR DESCRIPTION
**Pull request by yuriks**
They keep making my compiler print warnings.

### CODE REVIEW

**Comment by neobrain** [comment]
Is this important at all, really? This is just one thing we need to keep in mind when maintaining the fork, and I don't really see it important enough for that at all.

Why don't you instead submit this fix to upstream?

**Comment by yuriks** [comment]
Yes, it is very distracting when half the files you compile print out a spurious error message. What additional work does this cause in maintaining the fork?

I'll submit it upstream too.

**Comment by neobrain** [comment]
It's one thing to keep in mind when updating the boost version. If you're fine with me forgetting about it and blindly reverting this change upon the next upgrade, there's no harm in merging this for the time being though.

**Comment by yuriks** [comment]
Better that than the warnings. :P

**Comment by neobrain** [comment]
Fine then :)

**Comment by yuriks** [comment]
Also fixed upstream: https://github.com/boostorg/container/pull/23

**Pull request merged**
